version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - data-volume:/data
    environment:
      - USE_MOCK_APIS=true
      - DB_FILE=/data/articles_db.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  extension-dev:
    image: node:16
    ports:
      - "3000:3000"
    volumes:
      - ./extension:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    depends_on:
      - api

volumes:
  data-volume: 